/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookRouteImport } from './routes/book'
import { Route as CampRouteImport } from './routes/camp'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CoachesCornerRouteImport } from './routes/coaches-corner'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as EnquireRouteImport } from './routes/enquire'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LivezRouteImport } from './routes/livez'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as StoryTimeRouteImport } from './routes/story-time'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as BookIndexRouteImport } from './routes/book/index'
import { Route as BookThanksRouteImport } from './routes/book.thanks'
import { Route as CampIndexRouteImport } from './routes/camp/index'
import { Route as CampFuelRouteImport } from './routes/camp/fuel'
import { Route as CampGroupsRouteImport } from './routes/camp/groups'
import { Route as CampKitRouteImport } from './routes/camp/kit'
import { Route as CampMessagesRouteImport } from './routes/camp/messages'
import { Route as CampPrepareRouteImport } from './routes/camp/prepare'
import { Route as CampScheduleRouteImport } from './routes/camp/schedule'
import { Route as CampSquadRouteImport } from './routes/camp/squad'
import { Route as CampTodayRouteImport } from './routes/camp/today'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as CommunityCoachingRouteImport } from './routes/community/coaching'
import { Route as CommunityHallOfFameRouteImport } from './routes/community/hall-of-fame'
import { Route as CommunityHistoryRouteImport } from './routes/community/history'
import { Route as CommunityPartnersRouteImport } from './routes/community/partners'
import { Route as CommunityPerformanceRouteImport } from './routes/community/performance'
import { Route as CommunityTeamRouteImport } from './routes/community/team'
import { Route as HealthLiveRouteImport } from './routes/health.live'
import { Route as HealthReadyRouteImport } from './routes/health.ready'
import { Route as OpsIndexRouteImport } from './routes/ops/index'
import { Route as OpsPeopleRouteImport } from './routes/ops/people'
import { Route as VacationsIndexRouteImport } from './routes/vacations/index'
import { Route as VacationsLanzaroteRouteImport } from './routes/vacations/lanzarote'
import { Route as VacationsPadelRouteImport } from './routes/vacations/padel'
import { Route as VacationsTennisRouteImport } from './routes/vacations/tennis'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCachePurgeRouteImport } from './routes/api/cache.purge'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CampRoute = CampRouteImport.update({
  id: '/camp',
  path: '/camp',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesCornerRoute = CoachesCornerRouteImport.update({
  id: '/coaches-corner',
  path: '/coaches-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquireRoute = EnquireRouteImport.update({
  id: '/enquire',
  path: '/enquire',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LivezRoute = LivezRouteImport.update({
  id: '/livez',
  path: '/livez',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryTimeRoute = StoryTimeRouteImport.update({
  id: '/story-time',
  path: '/story-time',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const BookThanksRoute = BookThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => BookRoute,
} as any)
const CampIndexRoute = CampIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampRoute,
} as any)
const CampFuelRoute = CampFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => CampRoute,
} as any)
const CampGroupsRoute = CampGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => CampRoute,
} as any)
const CampKitRoute = CampKitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => CampRoute,
} as any)
const CampMessagesRoute = CampMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => CampRoute,
} as any)
const CampPrepareRoute = CampPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => CampRoute,
} as any)
const CampScheduleRoute = CampScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => CampRoute,
} as any)
const CampSquadRoute = CampSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => CampRoute,
} as any)
const CampTodayRoute = CampTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => CampRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityCoachingRoute = CommunityCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityHallOfFameRoute = CommunityHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityHistoryRoute = CommunityHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityPartnersRoute = CommunityPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityPerformanceRoute = CommunityPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityTeamRoute = CommunityTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => CommunityRoute,
} as any)
const HealthLiveRoute = HealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => HealthRoute,
} as any)
const HealthReadyRoute = HealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => HealthRoute,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const OpsPeopleRoute = OpsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OpsRoute,
} as any)
const VacationsIndexRoute = VacationsIndexRouteImport.update({
  id: '/vacations/',
  path: '/vacations/',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsLanzaroteRoute = VacationsLanzaroteRouteImport.update({
  id: '/vacations/lanzarote',
  path: '/vacations/lanzarote',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsPadelRoute = VacationsPadelRouteImport.update({
  id: '/vacations/padel',
  path: '/vacations/padel',
  getParentRoute: () => rootRouteImport,
} as any)
const VacationsTennisRoute = VacationsTennisRouteImport.update({
  id: '/vacations/tennis',
  path: '/vacations/tennis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCachePurgeRoute = ApiCachePurgeRouteImport.update({
  id: '/api/cache/purge',
  path: '/api/cache/purge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/camp': typeof CampRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/coaching': typeof CoachingRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enquire': typeof EnquireRoute
  '/health': typeof HealthRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/story-time': typeof StoryTimeRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/book/thanks': typeof BookThanksRoute
  '/camp/fuel': typeof CampFuelRoute
  '/camp/groups': typeof CampGroupsRoute
  '/camp/kit': typeof CampKitRoute
  '/camp/messages': typeof CampMessagesRoute
  '/camp/prepare': typeof CampPrepareRoute
  '/camp/schedule': typeof CampScheduleRoute
  '/camp/squad': typeof CampSquadRoute
  '/camp/today': typeof CampTodayRoute
  '/community/coaching': typeof CommunityCoachingRoute
  '/community/hall-of-fame': typeof CommunityHallOfFameRoute
  '/community/history': typeof CommunityHistoryRoute
  '/community/partners': typeof CommunityPartnersRoute
  '/community/performance': typeof CommunityPerformanceRoute
  '/community/team': typeof CommunityTeamRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/ops/people': typeof OpsPeopleRoute
  '/vacations/lanzarote': typeof VacationsLanzaroteRoute
  '/vacations/padel': typeof VacationsPadelRoute
  '/vacations/tennis': typeof VacationsTennisRoute
  '/book/': typeof BookIndexRoute
  '/camp/': typeof CampIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/vacations/': typeof VacationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/coaches': typeof CoachesRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/coaching': typeof CoachingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enquire': typeof EnquireRoute
  '/health': typeof HealthRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/story-time': typeof StoryTimeRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/book/thanks': typeof BookThanksRoute
  '/camp/fuel': typeof CampFuelRoute
  '/camp/groups': typeof CampGroupsRoute
  '/camp/kit': typeof CampKitRoute
  '/camp/messages': typeof CampMessagesRoute
  '/camp/prepare': typeof CampPrepareRoute
  '/camp/schedule': typeof CampScheduleRoute
  '/camp/squad': typeof CampSquadRoute
  '/camp/today': typeof CampTodayRoute
  '/community/coaching': typeof CommunityCoachingRoute
  '/community/hall-of-fame': typeof CommunityHallOfFameRoute
  '/community/history': typeof CommunityHistoryRoute
  '/community/partners': typeof CommunityPartnersRoute
  '/community/performance': typeof CommunityPerformanceRoute
  '/community/team': typeof CommunityTeamRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/ops/people': typeof OpsPeopleRoute
  '/vacations/lanzarote': typeof VacationsLanzaroteRoute
  '/vacations/padel': typeof VacationsPadelRoute
  '/vacations/tennis': typeof VacationsTennisRoute
  '/book': typeof BookIndexRoute
  '/camp': typeof CampIndexRoute
  '/community': typeof CommunityIndexRoute
  '/ops': typeof OpsIndexRoute
  '/vacations': typeof VacationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/camp': typeof CampRouteWithChildren
  '/coaches': typeof CoachesRoute
  '/coaches-corner': typeof CoachesCornerRoute
  '/coaching': typeof CoachingRoute
  '/community': typeof CommunityRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/enquire': typeof EnquireRoute
  '/health': typeof HealthRouteWithChildren
  '/healthz': typeof HealthzRoute
  '/history': typeof HistoryRoute
  '/livez': typeof LivezRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/portal': typeof PortalRoute
  '/privacy': typeof PrivacyRoute
  '/readyz': typeof ReadyzRoute
  '/story-time': typeof StoryTimeRoute
  '/terms': typeof TermsRoute
  '/travel': typeof TravelRoute
  '/book/thanks': typeof BookThanksRoute
  '/camp/fuel': typeof CampFuelRoute
  '/camp/groups': typeof CampGroupsRoute
  '/camp/kit': typeof CampKitRoute
  '/camp/messages': typeof CampMessagesRoute
  '/camp/prepare': typeof CampPrepareRoute
  '/camp/schedule': typeof CampScheduleRoute
  '/camp/squad': typeof CampSquadRoute
  '/camp/today': typeof CampTodayRoute
  '/community/coaching': typeof CommunityCoachingRoute
  '/community/hall-of-fame': typeof CommunityHallOfFameRoute
  '/community/history': typeof CommunityHistoryRoute
  '/community/partners': typeof CommunityPartnersRoute
  '/community/performance': typeof CommunityPerformanceRoute
  '/community/team': typeof CommunityTeamRoute
  '/health/live': typeof HealthLiveRoute
  '/health/ready': typeof HealthReadyRoute
  '/ops/people': typeof OpsPeopleRoute
  '/vacations/lanzarote': typeof VacationsLanzaroteRoute
  '/vacations/padel': typeof VacationsPadelRoute
  '/vacations/tennis': typeof VacationsTennisRoute
  '/book/': typeof BookIndexRoute
  '/camp/': typeof CampIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/vacations/': typeof VacationsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cache/purge': typeof ApiCachePurgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/book'
    | '/camp'
    | '/coaches'
    | '/coaches-corner'
    | '/coaching'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/enquire'
    | '/health'
    | '/healthz'
    | '/history'
    | '/livez'
    | '/login'
    | '/ops'
    | '/portal'
    | '/privacy'
    | '/readyz'
    | '/story-time'
    | '/terms'
    | '/travel'
    | '/book/thanks'
    | '/camp/fuel'
    | '/camp/groups'
    | '/camp/kit'
    | '/camp/messages'
    | '/camp/prepare'
    | '/camp/schedule'
    | '/camp/squad'
    | '/camp/today'
    | '/community/coaching'
    | '/community/hall-of-fame'
    | '/community/history'
    | '/community/partners'
    | '/community/performance'
    | '/community/team'
    | '/health/live'
    | '/health/ready'
    | '/ops/people'
    | '/vacations/lanzarote'
    | '/vacations/padel'
    | '/vacations/tennis'
    | '/book/'
    | '/camp/'
    | '/community/'
    | '/ops/'
    | '/vacations/'
    | '/api/auth/$'
    | '/api/cache/purge'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/coaches'
    | '/coaches-corner'
    | '/coaching'
    | '/contact'
    | '/cookies'
    | '/enquire'
    | '/health'
    | '/healthz'
    | '/history'
    | '/livez'
    | '/login'
    | '/portal'
    | '/privacy'
    | '/readyz'
    | '/story-time'
    | '/terms'
    | '/travel'
    | '/book/thanks'
    | '/camp/fuel'
    | '/camp/groups'
    | '/camp/kit'
    | '/camp/messages'
    | '/camp/prepare'
    | '/camp/schedule'
    | '/camp/squad'
    | '/camp/today'
    | '/community/coaching'
    | '/community/hall-of-fame'
    | '/community/history'
    | '/community/partners'
    | '/community/performance'
    | '/community/team'
    | '/health/live'
    | '/health/ready'
    | '/ops/people'
    | '/vacations/lanzarote'
    | '/vacations/padel'
    | '/vacations/tennis'
    | '/book'
    | '/camp'
    | '/community'
    | '/ops'
    | '/vacations'
    | '/api/auth/$'
    | '/api/cache/purge'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/book'
    | '/camp'
    | '/coaches'
    | '/coaches-corner'
    | '/coaching'
    | '/community'
    | '/contact'
    | '/cookies'
    | '/enquire'
    | '/health'
    | '/healthz'
    | '/history'
    | '/livez'
    | '/login'
    | '/ops'
    | '/portal'
    | '/privacy'
    | '/readyz'
    | '/story-time'
    | '/terms'
    | '/travel'
    | '/book/thanks'
    | '/camp/fuel'
    | '/camp/groups'
    | '/camp/kit'
    | '/camp/messages'
    | '/camp/prepare'
    | '/camp/schedule'
    | '/camp/squad'
    | '/camp/today'
    | '/community/coaching'
    | '/community/hall-of-fame'
    | '/community/history'
    | '/community/partners'
    | '/community/performance'
    | '/community/team'
    | '/health/live'
    | '/health/ready'
    | '/ops/people'
    | '/vacations/lanzarote'
    | '/vacations/padel'
    | '/vacations/tennis'
    | '/book/'
    | '/camp/'
    | '/community/'
    | '/ops/'
    | '/vacations/'
    | '/api/auth/$'
    | '/api/cache/purge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRouteWithChildren
  CampRoute: typeof CampRouteWithChildren
  CoachesRoute: typeof CoachesRoute
  CoachesCornerRoute: typeof CoachesCornerRoute
  CoachingRoute: typeof CoachingRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  EnquireRoute: typeof EnquireRoute
  HealthRoute: typeof HealthRouteWithChildren
  HealthzRoute: typeof HealthzRoute
  HistoryRoute: typeof HistoryRoute
  LivezRoute: typeof LivezRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  PortalRoute: typeof PortalRoute
  PrivacyRoute: typeof PrivacyRoute
  ReadyzRoute: typeof ReadyzRoute
  StoryTimeRoute: typeof StoryTimeRoute
  TermsRoute: typeof TermsRoute
  TravelRoute: typeof TravelRoute
  VacationsLanzaroteRoute: typeof VacationsLanzaroteRoute
  VacationsPadelRoute: typeof VacationsPadelRoute
  VacationsTennisRoute: typeof VacationsTennisRoute
  VacationsIndexRoute: typeof VacationsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCachePurgeRoute: typeof ApiCachePurgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camp': {
      id: '/camp'
      path: '/camp'
      fullPath: '/camp'
      preLoaderRoute: typeof CampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches-corner': {
      id: '/coaches-corner'
      path: '/coaches-corner'
      fullPath: '/coaches-corner'
      preLoaderRoute: typeof CoachesCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquire': {
      id: '/enquire'
      path: '/enquire'
      fullPath: '/enquire'
      preLoaderRoute: typeof EnquireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livez': {
      id: '/livez'
      path: '/livez'
      fullPath: '/livez'
      preLoaderRoute: typeof LivezRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-time': {
      id: '/story-time'
      path: '/story-time'
      fullPath: '/story-time'
      preLoaderRoute: typeof StoryTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/book/thanks': {
      id: '/book/thanks'
      path: '/thanks'
      fullPath: '/book/thanks'
      preLoaderRoute: typeof BookThanksRouteImport
      parentRoute: typeof BookRoute
    }
    '/camp/': {
      id: '/camp/'
      path: '/'
      fullPath: '/camp/'
      preLoaderRoute: typeof CampIndexRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/fuel': {
      id: '/camp/fuel'
      path: '/fuel'
      fullPath: '/camp/fuel'
      preLoaderRoute: typeof CampFuelRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/groups': {
      id: '/camp/groups'
      path: '/groups'
      fullPath: '/camp/groups'
      preLoaderRoute: typeof CampGroupsRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/kit': {
      id: '/camp/kit'
      path: '/kit'
      fullPath: '/camp/kit'
      preLoaderRoute: typeof CampKitRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/messages': {
      id: '/camp/messages'
      path: '/messages'
      fullPath: '/camp/messages'
      preLoaderRoute: typeof CampMessagesRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/prepare': {
      id: '/camp/prepare'
      path: '/prepare'
      fullPath: '/camp/prepare'
      preLoaderRoute: typeof CampPrepareRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/schedule': {
      id: '/camp/schedule'
      path: '/schedule'
      fullPath: '/camp/schedule'
      preLoaderRoute: typeof CampScheduleRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/squad': {
      id: '/camp/squad'
      path: '/squad'
      fullPath: '/camp/squad'
      preLoaderRoute: typeof CampSquadRouteImport
      parentRoute: typeof CampRoute
    }
    '/camp/today': {
      id: '/camp/today'
      path: '/today'
      fullPath: '/camp/today'
      preLoaderRoute: typeof CampTodayRouteImport
      parentRoute: typeof CampRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/coaching': {
      id: '/community/coaching'
      path: '/coaching'
      fullPath: '/community/coaching'
      preLoaderRoute: typeof CommunityCoachingRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/hall-of-fame': {
      id: '/community/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/community/hall-of-fame'
      preLoaderRoute: typeof CommunityHallOfFameRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/history': {
      id: '/community/history'
      path: '/history'
      fullPath: '/community/history'
      preLoaderRoute: typeof CommunityHistoryRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/partners': {
      id: '/community/partners'
      path: '/partners'
      fullPath: '/community/partners'
      preLoaderRoute: typeof CommunityPartnersRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/performance': {
      id: '/community/performance'
      path: '/performance'
      fullPath: '/community/performance'
      preLoaderRoute: typeof CommunityPerformanceRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/team': {
      id: '/community/team'
      path: '/team'
      fullPath: '/community/team'
      preLoaderRoute: typeof CommunityTeamRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/health/live': {
      id: '/health/live'
      path: '/live'
      fullPath: '/health/live'
      preLoaderRoute: typeof HealthLiveRouteImport
      parentRoute: typeof HealthRoute
    }
    '/health/ready': {
      id: '/health/ready'
      path: '/ready'
      fullPath: '/health/ready'
      preLoaderRoute: typeof HealthReadyRouteImport
      parentRoute: typeof HealthRoute
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/people': {
      id: '/ops/people'
      path: '/people'
      fullPath: '/ops/people'
      preLoaderRoute: typeof OpsPeopleRouteImport
      parentRoute: typeof OpsRoute
    }
    '/vacations/': {
      id: '/vacations/'
      path: '/vacations'
      fullPath: '/vacations/'
      preLoaderRoute: typeof VacationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations/lanzarote': {
      id: '/vacations/lanzarote'
      path: '/vacations/lanzarote'
      fullPath: '/vacations/lanzarote'
      preLoaderRoute: typeof VacationsLanzaroteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations/padel': {
      id: '/vacations/padel'
      path: '/vacations/padel'
      fullPath: '/vacations/padel'
      preLoaderRoute: typeof VacationsPadelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacations/tennis': {
      id: '/vacations/tennis'
      path: '/vacations/tennis'
      fullPath: '/vacations/tennis'
      preLoaderRoute: typeof VacationsTennisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cache/purge': {
      id: '/api/cache/purge'
      path: '/api/cache/purge'
      fullPath: '/api/cache/purge'
      preLoaderRoute: typeof ApiCachePurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookThanksRoute: typeof BookThanksRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookThanksRoute: BookThanksRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

interface CampRouteChildren {
  CampFuelRoute: typeof CampFuelRoute
  CampGroupsRoute: typeof CampGroupsRoute
  CampKitRoute: typeof CampKitRoute
  CampMessagesRoute: typeof CampMessagesRoute
  CampPrepareRoute: typeof CampPrepareRoute
  CampScheduleRoute: typeof CampScheduleRoute
  CampSquadRoute: typeof CampSquadRoute
  CampTodayRoute: typeof CampTodayRoute
  CampIndexRoute: typeof CampIndexRoute
}

const CampRouteChildren: CampRouteChildren = {
  CampFuelRoute: CampFuelRoute,
  CampGroupsRoute: CampGroupsRoute,
  CampKitRoute: CampKitRoute,
  CampMessagesRoute: CampMessagesRoute,
  CampPrepareRoute: CampPrepareRoute,
  CampScheduleRoute: CampScheduleRoute,
  CampSquadRoute: CampSquadRoute,
  CampTodayRoute: CampTodayRoute,
  CampIndexRoute: CampIndexRoute,
}

const CampRouteWithChildren = CampRoute._addFileChildren(CampRouteChildren)

interface CommunityRouteChildren {
  CommunityCoachingRoute: typeof CommunityCoachingRoute
  CommunityHallOfFameRoute: typeof CommunityHallOfFameRoute
  CommunityHistoryRoute: typeof CommunityHistoryRoute
  CommunityPartnersRoute: typeof CommunityPartnersRoute
  CommunityPerformanceRoute: typeof CommunityPerformanceRoute
  CommunityTeamRoute: typeof CommunityTeamRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityCoachingRoute: CommunityCoachingRoute,
  CommunityHallOfFameRoute: CommunityHallOfFameRoute,
  CommunityHistoryRoute: CommunityHistoryRoute,
  CommunityPartnersRoute: CommunityPartnersRoute,
  CommunityPerformanceRoute: CommunityPerformanceRoute,
  CommunityTeamRoute: CommunityTeamRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface HealthRouteChildren {
  HealthLiveRoute: typeof HealthLiveRoute
  HealthReadyRoute: typeof HealthReadyRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthLiveRoute: HealthLiveRoute,
  HealthReadyRoute: HealthReadyRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface OpsRouteChildren {
  OpsPeopleRoute: typeof OpsPeopleRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsPeopleRoute: OpsPeopleRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRouteWithChildren,
  CampRoute: CampRouteWithChildren,
  CoachesRoute: CoachesRoute,
  CoachesCornerRoute: CoachesCornerRoute,
  CoachingRoute: CoachingRoute,
  CommunityRoute: CommunityRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  EnquireRoute: EnquireRoute,
  HealthRoute: HealthRouteWithChildren,
  HealthzRoute: HealthzRoute,
  HistoryRoute: HistoryRoute,
  LivezRoute: LivezRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  PortalRoute: PortalRoute,
  PrivacyRoute: PrivacyRoute,
  ReadyzRoute: ReadyzRoute,
  StoryTimeRoute: StoryTimeRoute,
  TermsRoute: TermsRoute,
  TravelRoute: TravelRoute,
  VacationsLanzaroteRoute: VacationsLanzaroteRoute,
  VacationsPadelRoute: VacationsPadelRoute,
  VacationsTennisRoute: VacationsTennisRoute,
  VacationsIndexRoute: VacationsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCachePurgeRoute: ApiCachePurgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
